2022-03-04 20:43:56,918 ERROR: Exception on /upload_file [POST] [in C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\62821\Documents\GitHub\4p-flask\app\routes.py", line 333, in upload
    request.save_book_to_database(
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_webio\__init__.py", line 237, in save_book_to_database
    pe.save_book_as(**params)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\core.py", line 112, in save_book_as
    return sources.save_book(book, **dest_keywords)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\internal\core.py", line 55, in save_book
    return _save_any(a_source, book)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\internal\core.py", line 59, in _save_any
    a_source.write_data(instance)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\plugins\sources\db_sources.py", line 106, in write_data
    arender.render_book_to_stream(
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\plugins\renderers\sqlalchemy.py", line 63, in render_book_to_stream
    save_data(importer, to_store, file_type=self._file_type, **keywords)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\io.py", line 143, in save_data
    writer.write(to_store)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\writer.py", line 42, in write
    self.writer.write(incoming_dict)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\plugin_api\abstract_writer.py", line 10, in write
    sheet_writer = self.create_sheet(sheet_name)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\database\importers\sqlalchemy.py", line 95, in create_sheet
    raise Exception(
Exception: Sheet: Lembar1 does not match any given tables.Please be aware of case sensitivity.
2022-03-04 20:48:37,758 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-04 20:48:48,149 ERROR: Exception on /upload_file [POST] [in C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\62821\Documents\GitHub\4p-flask\app\routes.py", line 333, in upload
    request.save_book_to_database(
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_webio\__init__.py", line 237, in save_book_to_database
    pe.save_book_as(**params)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\core.py", line 112, in save_book_as
    return sources.save_book(book, **dest_keywords)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\internal\core.py", line 55, in save_book
    return _save_any(a_source, book)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\internal\core.py", line 59, in _save_any
    a_source.write_data(instance)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\plugins\sources\db_sources.py", line 106, in write_data
    arender.render_book_to_stream(
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\plugins\renderers\sqlalchemy.py", line 63, in render_book_to_stream
    save_data(importer, to_store, file_type=self._file_type, **keywords)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\io.py", line 143, in save_data
    writer.write(to_store)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\writer.py", line 42, in write
    self.writer.write(incoming_dict)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\plugin_api\abstract_writer.py", line 10, in write
    sheet_writer = self.create_sheet(sheet_name)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\database\importers\sqlalchemy.py", line 95, in create_sheet
    raise Exception(
Exception: Sheet: Lembar1 does not match any given tables.Please be aware of case sensitivity.
2022-03-04 20:51:34,266 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-04 20:51:54,650 ERROR: Exception on /download_table/1 [GET] [in C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\62821\Documents\GitHub\4p-flask\app\routes.py", line 349, in download_table
    return excel.make_response_from_query_sets(query_sets, column_names, "csv")
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_webio\__init__.py", line 434, in make_response_from_query_sets
    file_stream = pe.save_as(query_sets=query_sets, column_names=column_names,
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\core.py", line 77, in save_as
    sheet_stream = sources.get_sheet_stream(**source_keywords)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\internal\core.py", line 21, in get_sheet_stream
    sheets = a_source.get_data()
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\plugins\sources\querysets.py", line 72, in get_data
    data = get_data(
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\io.py", line 86, in get_data
    data, _ = _get_data(
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\io.py", line 105, in _get_data
    return load_data(**keywords)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\io.py", line 208, in load_data
    result[key] = list(result[key])
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\sheet.py", line 55, in to_array
    for row_index, row in enumerate(self.row_iterator()):
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\reader.py", line 123, in row_iterator
    yield from self._native_sheet.row_iterator()
TypeError: 'Post' object is not iterable
2022-03-04 20:57:23,165 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-04 20:57:27,704 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-04 20:58:16,623 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-04 20:58:52,706 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-04 21:03:27,901 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-04 21:04:01,711 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-04 21:08:09,529 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-04 21:09:21,400 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
